Fix affiliations
pymedphys/pymedphys pull request #1758
Opened 2022-10-09 05:08 UTC by Matthew-Jennings

Add cities to affiliations
Add "the" to RAH
Expand USA

As per https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1272261778

-----

Can you all please check and, if necessary, correct the edits I've made to your particular affiliation? Some additional notes:

@SimonBiggs, would you mind confirming whether "CancerCare Partners" is appropriate for @msobolewski, given Riverina Cancer Centre is listed for Jacob? Also, is it "Wagga Wagga" if we use CCP, or their headquarters?

@pchlap, I thought it might be better to expand to the full name for the Ingham Institute, but please feel free to revert to the original wording.

2022-10-09 05:19 UTC, guanfada commented
Mine is correct. Thank you @Matthew-Jennings

2022-10-09 05:49 UTC, sjswerdloff approved these changes
That is the correct city for my affiliation

2022-10-09 06:44 UTC, ayalalazaro approved these changes
Mine is correct too.

2022-10-09 14:01 UTC, kingrpaul commented
From:   Painless Skin Cancer Treatment, Mississippi, USA
To: Painless Skin Cancer Treatment Center, Meridian, Mississippi, United States of America

Thanks.

2022-10-09 14:24 UTC, guanfada requested changes
add "Connecticut, " after "New Haven, "

2022-10-09 21:14 UTC, pchlap approved these changes
Thanks, @Matthew-Jennings, yes the full name of Ingham is better.

2022-10-09 21:26 UTC, SimonBiggs commented on paper.md
> +  - name: CancerCare Partners, Wagga Wagga, Australia
```suggestion
  - name: CancerCare Partners, Sydney, Australia
```

2022-10-09 21:27 UTC, SimonBiggs commented on paper.md
> +  - name: Ingham Institute for Applied Medical Research, Liverpool, Australia
```suggestion
  - name: Ingham Institute for Applied Medical Research, Sydney, Australia
```

2022-10-09 23:07 UTC, Matthew-Jennings commented
@SimonBiggs, are you sure about the Ingham Institute "city" change? 
![image](https://user-images.githubusercontent.com/19767103/194783739-08d713dd-5fa9-460b-a0ea-b34f8370cc68.png)

2022-10-09 23:56 UTC, crcrewso approved these changes

2022-10-10 01:45 UTC, SimonBiggs commented
> @SimonBiggs, are you sure about the Ingham Institute "city" change? ![image](https://user-images.githubusercontent.com/19767103/194783739-08d713dd-5fa9-460b-a0ea-b34f8370cc68.png)

I stand corrected:

https://en.m.wikipedia.org/wiki/City_of_Liverpool_(New_South_Wales)

2022-10-10 03:04 UTC, guanfada approved these changes

2022-10-10 18:09 UTC, rembishj submitted a review, later dismissed
sorry for the delay with the ORCID... mine is 0000-0002-6508-4175

2022-10-11 03:41 UTC, merged