Dicom rt visualisation
pymedphys/pymedphys pull request #1885
Opened 2024-12-22 05:20 UTC by Matthew-Jennings

I thought this would be a nice tool to have to:

- Enhance the user's gamma experience if eventually it is expanded to interactively plot gamma data
- Help showcase future DVH work, e.g.:
  - structure interpolation
  - dose/ct interpolation?
  - end capping,
  - etc.

I've spent a fair bit of time trying to make this pretty snappy, with some success (at least on my PC!) You can test it out by running:

```bash
poetry run streamlit run \<path-to-pymedphys>\pymedphys\lib\pymedphys\_experimental\dicomrtvisualisation\visualise.py
```

Screenshot:
![image](https://github.com/user-attachments/assets/6223b0f5-b717-45e8-8b44-fd0db8f03009)

2024-12-22 05:21 UTC, Matthew-Jennings commented
(Expecting this to land after #1884 , hence the CHANGELOG update, etc.

2025-01-22 23:34 UTC, Matthew-Jennings commented
This is probably ready enough, at least for experimental.

Thoughts on requirements for making non-experimental? Other than docs.

2025-01-22 23:48 UTC, SimonBiggs commented
My recommendation for migrating a frontend app like this out of experimental would be for it to have been dogfooded within your organisation by multiple people over order months as well as including at least one e2e streamlit test that captures a core interface utility with a relevant baseline.

2025-01-23 00:14 UTC, Matthew-Jennings commented
> My recommendation for migrating a frontend app like this out of experimental would be for it to have been dogfooded within your organisation by multiple people over order months as well as including at least one e2e streamlit test that captures a core interface utility with a relevant baseline.

Fair enough.

None of that is going to happen on my end, haha. But no issue with it being in experimental.

2025-02-07 05:41 UTC, sjswerdloff requested changes
I think we need to make whatever change is required so that the version will be 0.42.0-dev0, but other than that, wow, this is really handy.
I tried it out on some sample data I had lying around (it's on Zenodo as well), and it was incredibly fast (Apple M1 MacBook Pro).

2025-02-07 05:41 UTC, sjswerdloff commented on .github/workflows/library.yml
> +          npm install -g pyright@1.1.386
Any particular reason for this version?  Current version is 1.1.393.
If there's a reason for pinning, I prefer to put in a comment explaining why (I don't think an explanation is needed for keeping less than a Major version, the implication with Major version change is an API change).

2025-02-07 05:41 UTC, sjswerdloff commented on lib/pymedphys/_version.py
> +version_info = [0, 41, 0]
this suggests that something needs to change in a configuration file to bump up to 0, 42, 0, "dev0"

2025-02-07 05:41 UTC, sjswerdloff commented on lib/pymedphys/docs/_config.yml
> +# parse:
why did this have to be commented out?  Was this part of the 0.41 release and already discussed?

2025-02-07 05:41 UTC, sjswerdloff commented on pyproject.toml
> +version = "0.41.0"
bump to 0.42.0-dev0? or is this automated (sorry, been a while).

2025-02-08 06:30 UTC, Matthew-Jennings commented on lib/pymedphys/docs/_config.yml
> +# parse:
Sorry, I think I was trying to resolve some of the documentation warnings that sphinx throws when building. You know, for funsies. But didn't really get anywhere, and really should've been working on a different branch. I've reverted those changes.

2025-02-08 06:33 UTC, Matthew-Jennings commented
> I think we need to make whatever change is required so that the version will be 0.42.0-dev0, but other than that, wow, this is really handy. I tried it out on some sample data I had lying around (it's on Zenodo as well), and it was incredibly fast (Apple M1 MacBook Pro).

I think I've made all the necessary changes. Sorry for that version miss!

I'm glad to read you liked it!

2025-02-08 06:38 UTC, sjswerdloff approved these changes
LGTM

2025-02-08 06:41 UTC, merged